dist: focal

before_install:
  - gem install package_cloud

script:
  - sudo docker run -v "$(pwd)/:/build/" -w /build/ debian/unstable ./travis-build.sh

after_success:
  - package_cloud push nitrux/testing/debian/trixie *.deb

branches:
  only:
    - main

notifications:
  email: false
